name: first workflow

on:
  workflow_dispatch

jobs:


  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo this is a multi-line script
