name: first workflow

env:
  WORKFLOW_VAR: "This is workflow variable"

on:
  workflow_dispatch

jobs:


  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: greet a user with hello world function
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Ram'
      - name: the greeting time
        run: |
          echo "The time of the greeting was at: ${{steps.greetings.outout.time }}"

  secondJob:
    runs-on: ubuntu-latest
    needs: firstJob
    env:
      JOB_VAR: "This is job variable"
    steps:
      - name: secondJob script
        shell: bash
        env:
          STEP_VAR: "This is step variable"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..." echo "The following are default environment variables:"
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF
